---
# tasks file for notejam-deploy
  - name: Get infos on container
    docker_container_info:
      name: "{{ docker_container_name }}"
    register: result

  - name: Stop container
    docker_container:
      name: "{{ docker_container_name }}"
      state: stopped
    when: result.exists

  - name: Remove container
    docker_container:
      name: "{{ docker_container_name }}"
      state: absent
    when: result.exists

  - name: Pull an image
    docker_image:
      name: "{{ docker_image_name }}:{{ docker_image_tag }}"
      source: pull
  - name: Create volume
    docker_volume:
      name: "{{ docker_volume_name }}"
      driver: local
  - name: Run notejam Docker container
    docker_container:
      name: "{{ docker_container_name }}"
      image: "{{ docker_image_name }}:{{ docker_image_tag }}"
      state: started
      ports:
        - "3000:3000"
      volumes:
        - "{{ docker_volume_name }}:/usr/db"

